name: ficreview
services:
   pg:
      image: postgres:17
      restart: unless-stopped
      container_name: fic_postgres
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DATABASE}
      volumes:
         - pg_data:/var/lib/postgresql/data
      ports:
         - 5432:5432
      networks:
         - net
   redis:
      image: redis:7.2.7-alpine
      container_name: fic_redis
      restart: unless-stopped
      command: redis-server --requirepass ${REDIS_PASSWORD}
      ports:
         - 6379:6379
      volumes:
         - redis_data:/data
      networks:
         - net
volumes:
   pg_data:
   redis_data:
networks:
   net:
