export enum TokenType {
   EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
   PASSWORD_RESET = 'PASSWORD_RESET'
}

export const TOKEN_TTL = {
   [TokenType.EMAIL_VERIFICATION]: 60 * 20,
   [TokenType.PASSWORD_RESET]: 60 * 5,
   REFRESH_TOKEN: 60 * 60 * 24 * 7,
   ACCESS_TOKEN: 60 * 30
};

export const REFRESH_TOKEN_COOKIE_NAME = 'refreshToken';
export const EMAIL_VERIFY_RESEND_COOLDOWN = 60 * 1.5;
export const EMAIL_VERIFICATION_TOKEN_LENGTH = 8;

export const VALIDATION_LENGTH = {
   PASSWORD_MIN: 8,
   USERNAME_MIN: 4,
   FANFIC_TITLE_MIN: 10,
   FANFIC_TITLE_MAX: 255,
   FANFIC_DESCRIPTION_MAX: 3000,
   FANDOM_MIN: 3,
   FANDOM_MAX: 100,
   TAGS_PAIRINGS_MAX: 20,
   TAGS_PAIRINGS_MAX_LENGTH: 50,
   CHAPTER_MAX: 250,
   CHAPTER_CONTENT_MAX: 5242880
};
