export enum TokenType {
   EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
   PASSWORD_RESET = 'PASSWORD_RESET'
}

export const TOKEN_TTL = {
   [TokenType.EMAIL_VERIFICATION]: 60 * 20,
   [TokenType.PASSWORD_RESET]: 60 * 5,
   REFRESH_TOKEN: 60 * 60 * 24 * 7,
   ACCESS_TOKEN: 60 * 30
};

export const REFRESH_TOKEN_COOKIE_NAME = 'refreshToken';
export const EMAIL_VERIFY_RESEND_COOLDOWN = 60 * 1.5;
export const EMAIL_VERIFICATION_TOKEN_LENGTH = 8;
